apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fmt-java
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: albertou/fmtok8s-java-function:latest
          env:
            - name: HELLO
              value: "Java Sample v1"
